org.slf4j.simpleLogger.defaultOutputStream=System.out
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.levelInBrackets=true
org.slf4j.simpleLogger.defaultLogLevel=INFO
org.slf4j.simpleLogger.log.io.javalin=INFO
org.slf4j.simpleLogger.log.org.eclipse.jetty=INFO
org.slf4j.simpleLogger.log.com.example.rag=INFO
